### ISSUE TITLE
unable to send a free text

### ISSUE THREAD

**Issue by stoopdapoop** [typpo/textbelt#118]
when I try to send an sms, I get the error: 
"This Textbelt endpoint now requires a 'key' param. Please go to https://textbelt.com to sign up for an API key."

I signed up and got an API key, but now I get the "Out of quota" error message.

Is there no longer a way to send a free sms?

**Comment by ILABUTK** [comment]
Same here. I just tested and got the same error.

**Comment by daluu** [comment]
I'd assume probably the website isn't clear on what to do when signing up with new key. If you follow the discussions in Github issues for this repo, you'll see that the public service is no longer free. You can use it totally free if you self host the service yourself on some server or in the cloud.

For the public service that requires API key, read the part at the end where you sign up for API key, there's a note `If you already have one, add funds to an existing key.` Supposedly, one can infer that for new keys created, you then next have to "add funds" to it before use. I'd assume the email or webpage that returns the new key would also mention adding funds but maybe that part was overlooked/omitted somehow (or in fine print tiny text).

**Comment by ILABUTK** [comment]
Thanks for the clarification!

**Comment by typpo** [comment]
@daluu is correct.  The hosted version on textbelt.com requires paid credits as of 2017, unfortunately, due to spam and abuse.  However, Textbelt is still free because it's open source and you can run it on your own server.

I will take your feedback and update the API response or README to be clearer.  The second sentence in this project's readme is 
"[Textbelt] uses a free mechanism for sending texts, different from the more reliable paid version available at https://textbelt.com".  In other words, textbelt.com is running software that is distinct from this open-source project (it's more reliable but not free).
