### ISSUE TITLE
Is there a way to set the sending phone number? 

### ISSUE THREAD

**Issue by paulbeard** [typpo/textbelt#124]
The system in which I hope to use this is "secured" to the point where it only accepts texts from specified phone numbers. I don't see if there is a way to set that. In email it would just be a matter of writing a header, like "Reply-to" but I'm not sure about this.

**Comment by typpo** [comment]
Hi Paul, there isn't a way to set the sending phone number.  Carriers typically don't support this due to potential for abuse.

**Comment by paulbeard** [comment]
> On Aug 13, 2018, at 8:41 AM, Ian Webster <notifications@github.com> wrote:
> 
> Hi Paul, there isn't a way to set the sending phone number. Carriers typically don't support this due to potential for abuse.
> 
> 


Rats. The idea was to programmatically control/communicate with a vehicle-based GPS tracker but it is set to only receive from specified numbers. Back to the drawing board, I guess. 

Thanks.

**Comment by typpo** [comment]
You could definitely do this with a paid API like Twilio that lets you buy particular phone numbers

**Comment by paulbeard** [comment]
> On Aug 13, 2018, at 8:52 AM, Ian Webster <notifications@github.com> wrote:
> 
> You could definitely do this with a paid API like Twilio that lets you buy particular phone numbers
> 
> 

Yeah, I was hoping not to pay for that. It may not be possible to DIY this as cheaply as that, it seems. A SIM card and the unit to run it were the only real expenses. A scriptable phone or desktop app that uses the phone’s number would work, if one exists.

**Comment by Q02e** [comment]
Hi Paul,

Im glad i found this post, as i am in the same boat as you and have been searching for a solution to this for quite some time now.

Have you found any way you could do this or a solution to this problem?
Im assuming you dont want to use a paid service such as Twilio for privacy reasons.

I haven tried Textbelt as yet, im guessing the _sending_ numbers are complete random everytime?

**Comment by daluu** [comment]
Aside from providing specifically an actual phone number (not email), isn't the sender info provided here for manual hosting textbelt?

https://github.com/typpo/textbelt/blob/master/lib/config.js#L2

Just set the email to have a phone number in it? And if the number is from a provider that offers SMS to email gateway (which means likely a cell phone number from a supported carrier), you can then actually provide the email (gateway) address for that number. Granted whether the replies go through or whether the original message gets sent this way depends on the destination carriers whether they spam block the from address or not.

And in the case of fake "from address" but with valid number in the address, at least the recipient knows who it came from to manually reply, but they couldn't reply directly to the message since that would go nowhere.

**Comment by paulbeard** [comment]
> On Sep 6, 2018, at 3:47 PM, Q02e <notifications@github.com> wrote:
> 
> Have you found any way you could do this or a solution to this problem?

No, I never found a solution for this, outside of a paid service. And testing meant several days of “Message undeliverable” emails from all the carriers whose gateways got my test message.

**Comment by virtualducttape** [comment]
@paulbeard @Q02e So far the best shot at a real "free SMS" service (in the US at least), seems like it might be Google Voice (the old phone system, not the new Google Home TTS system, I really wish they'd start picking more unique names for things...). I believe there are a couple possible avenues for that system, either through the Google Voice API with something like https://github.com/pettazz/pygooglevoice/ , or through Hangouts, which doesn't directly support an API, but I believe may be accessible through XMPP messages (from what I've seen, this requires you to start a chat with the target user beforehand, and then using something like pidgin to capture the unique JID representing the conversation between those specific users, see https://community.home-assistant.io/t/notifications-via-google-hangouts/64773 for some discussion about this).

Textbelt is a good "backup" option for one way messaging... I might wind up having to go this route if the ability to connect to the Google Voice number winds up being too unstable.

@daluu That is definitely an interesting point... it would probably depend on if the carriers actually communicate between one another using the number@carrier.com as the "from address" or if they use some other system/parameter to communicate the sending number. I know there are 3rd party "number spoofer" programs that you can pay for, however it seems to me that if it was truly as easy as setting the sending address, we'd also see a lot more ad-supported "spoofers", because there's a large unserved market who would use that service but aren't willing to pay for it. Unfortunately I don't have TextBelt up and running so I can't easily test it, but if I wind up falling back to this as my main option, I'll have to investigate that possibility.
