### ISSUE TITLE
Your service is being used for phishing spam

### ISSUE THREAD

**Issue by vistun** [typpo/textbelt#155]
![image](https://user-images.githubusercontent.com/1464233/93695275-b9280680-fac9-11ea-983f-2fe7cf24c58c.png)

**Comment by typpo** [comment]
This sender is your mobile service provider via email-to-SMS gateway.  The free hosted Textbelt service used email-to-SMS gateways up until 2017, which is why you received a Textbelt message from this number in 2015.  Unfortunately, the phishing message you just received could be an email sent by anyone, and is not Textbelt affiliated.

**Comment by vistun** [comment]
Brilliant! Apologies for the premature accusation.
