### ISSUE TITLE
Is it possible to remove FRM:root and SUBJ:txt from the text SMS

### ISSUE THREAD

**Issue by ppatel03** [typpo/textbelt#59]
My app is sending SMS using the query : message=message_value&number=number_value

The resulting SMS contains the following 
FRM:root
SUBJ:txt
MSG:This is a sample message.

Is it possible to remove or modify FRM and SUBJ field.

**Comment by daluu** [comment]
(Part of) this may be the result of recent changes as mentioned in a recent comment under issue 11.

Frankly, I don't think your request on the removal part is a good one for services that send SMS via an email to SMS gateway, because emails typically expect those fields. Try sending one yourself by emailing to an SMS gateway, for example a reference: https://en.wikipedia.org/wiki/SMS_gateway

I'm not sure of any APIs based off this method allow configuration of subject & from fields (there aren't many that are free, most are paid and may or may not be based off this method). I know one other, AutoSMS, does not allow such a request of yours.

If you desire removal of such fields, better to find a different service, perhaps one not based off email to SMS gateways.

But, modifying those fields with a custom message isn't a bad idea. Let's see what others think.

Though of course, if you're using the self hosted option, you are welcome to make code change to make those fields configurable or removed (at your own expense).

**Comment by typpo** [comment]
Unfortunately FRM and SUBJ are built in. Some cell providers reject messages that don't have those fields set, and right now there is no way to customize them.

We could make the SUBJ field customizable, but a little nervous about making FRM customizable due to abuse.

One alternative is to host your own Textbelt server and set the From and Subject fields yourself in `lib/text.js.`
